H1 = (90-100)
H2 = (88)
H3 = (77)
H4 = (66)
H5 = (56)
H6 = (46)
H7 = (33)
H8 = (33)
Maths = int(input('What result did you get in Maths?: '))
Irish = int(input('What result did you get in Irish?: '))
English = int(input('What result did you get in English?: '))
French = int(input('What result did you get in French?: '))
ComputerScience = int(input('What result did you get in Computer Science?: '))
Physics = int(input('What result did you get in Physics?: '))
TotalPoints = int(Maths+Irish+English+French+ComputerScience+Physics)
print('Your total Leaving Cert points is: ',TotalPoints)